"""add user_id to tasks

Revision ID: 0f1305d63cb0
Revises: 
Create Date: 2026-06-20 17:29:24.448260

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f1305d63cb0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('task_table')
    op.drop_table('new_user_table')
    op.drop_index(op.f('ix_Book_Detail_ref_cd'), table_name='Book_Detail')
    op.drop_table('Book_Detail')
    op.add_column('User_Tasks', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'User_Tasks', 'User_table', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'User_Tasks', type_='foreignkey')
    op.drop_column('User_Tasks', 'user_id')
    op.create_table('Book_Detail',
    sa.Column('ref_cd', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('count', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('lang', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('ref_cd', name=op.f('Book_Detail_pkey'))
    )
    op.create_index(op.f('ix_Book_Detail_ref_cd'), 'Book_Detail', ['ref_cd'], unique=False)
    op.create_table('new_user_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hash_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mob', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('new_user_table_pkey'))
    )
    op.create_table('task_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('section', sa.VARCHAR(length=1), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('task_table_pkey'))
    )
    # ### end Alembic commands ###
